### Quiz

#### Q1. 다음과 같은 리스트를 이용하여 넘파이 배열을 만들고
전체 갯수, 차원, 데이터형, 구조를 출력하여라
```

['강아지', '원숭이', '꽃', '45', '100']

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3
전체 구조  ? (5,)
```

In [1]:
import numpy as np

In [62]:
a = np.array(['강아지', '원숭이', '꽃', '45', '100'])
print(a)
print(a.ndim)
print(len(a))
print(type(a))
print(a.shape)
print(a.dtype) #찾아서 함

['강아지' '원숭이' '꽃' '45' '100']
1
5
<class 'numpy.ndarray'>
(5,)
<U3


In [63]:
#강사님
a = np.array(['강아지', '원숭이', '꽃', '45', '100'])
a, a.ndim, a.size, type(a), a.dtype, a.shape

(array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3'),
 1,
 5,
 numpy.ndarray,
 dtype('<U3'),
 (5,))

#### Q2. np.ones()를 이용하여
2행 3열의 넘파이 배열을 생성하여라

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
print(np.ones((2,3))) #찾아서함
#필터를 거친 후 특정 값을 유지하기 위해. 

[[1. 1. 1.]
 [1. 1. 1.]]


#### Q3. np.arange(), np.reshape()를 이용하여
다음과 같은 넘파이 배열을 생성하여라
```
array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])
```

In [13]:
a = np.arange(51, 81)
a.reshape(6,5) #스스로함

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

In [64]:
#강사님
np.arange(51, 81).reshape(-1,5)

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

#### Q4. Q3의 넘파이 배열의 자료형을
float로 변경하고 데이터형을 출력하여라
```
array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])
```
-------------------------------------  

dtype('float64')

In [14]:
a = np.arange(51, 81, dtype=float).reshape(6,5)
a, a.dtype #찾아서 함

(array([[51., 52., 53., 54., 55.],
        [56., 57., 58., 59., 60.],
        [61., 62., 63., 64., 65.],
        [66., 67., 68., 69., 70.],
        [71., 72., 73., 74., 75.],
        [76., 77., 78., 79., 80.]]),
 dtype('float64'))

In [ ]:
#강사님
arr = arr.astype(float)
arr.dtype

#### Q5. 다음과 같이 넘파이 배열을 생성한 후 1차원 배열로 변경하고 슬라이싱하여라 

```
array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
       
array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])


array([23, 45, 67,  8,  4,  6])
```       

In [23]:
a = np.array([1, 4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10]).reshape(3,4)
a #혼자해냄

array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])

In [27]:
b = a.flatten()
b

array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])

In [30]:
b[5:11] #혼자 해냄

array([23, 45, 67,  8,  4,  6])

In [ ]:
#강사님꺼 보기

#### Q6. 다음과 같은 넘파이 배열을 생성한 후 아이템을 교체하여라 

```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

```

In [35]:
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a[0] = 10
a[7:10] = 0
a #혼자해냄

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

#### Q7. 2자리의 숫자로 구성된 넘파이 배열(5행5열)을 만들어라. 숫자는 난수를 이용한다. 

```
[[63 85 71 67 15]
 [31 81 69 17 97]
 [25 41 33 23 39]
 [39 43 59 33 43]
 [23 51 65 91 23]]

```

In [36]:
a = np.random.randint(10, 100, (5,5))
a

array([[48, 64, 61, 97, 70],
       [33, 78, 50, 70, 27],
       [91, 69, 60, 96, 90],
       [17, 42, 38, 29, 52],
       [49, 18, 58, 64, 90]])

#### Q8. 1~100 사이의 정수중 7개의 숫자를 무작위로 추출한 후 가장 큰값과 가장 작은 값을 출력하여라.
[91, 65, 14, 66, 65, 98, 34]

max = 98
min = 14

In [39]:
a = np.random.randint(1, 101, 7)
a, a.max() ,a.min() #혼자해냄

(array([94, 69, 55, 55,  9, 77, 73]), 94, 9)

In [65]:
a = np.random.randint(1, 101, 7)
a, np.max(a), np.min(a)

(array([ 4, 14, 58, 92, 70, 62, 54]), 92, 4)

#### Q9. 다음과 같은 3개의 넘파이 배열을 생성한 후 다음과 같이 합쳐라
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]


[[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]]


[[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]]
```
 ----------
  Result1 
```
 [[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
  [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
  [ 7,  8,  9, 17, 18, 19, 27, 28, 29]] 
```

  ----------
  Result2
```
 [[ 1,  2,  3],
  [ 4,  5,  6],
  [ 7,  8,  9],
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19],
  [21, 22, 23],
  [24, 25, 26],
  [27, 28, 29]]
```

In [66]:
a = np.arange(1, 10).reshape(3,3)
b = np.arange(11, 20).reshape(3,3)
c = np.arange(21, 30).reshape(3,3)
a, b, c

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]),
 array([[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]))

In [48]:
d = a[0]+b[0]+c[0]
d

array([33, 36, 39])

In [67]:
#강사님
#result1
d = np.hstack((a,b,c))
d

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
       [ 7,  8,  9, 17, 18, 19, 27, 28, 29]])

In [69]:
#result2
e = np.vstack((a,b,c))
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

#### Q10. 아래와 같이 넘파이 배열을 생성한 후 50보다 큰 숫자만 필터링하여라. 

```
arr = np.random.choice(100, 40, replace=False)

Before => 

[40, 63,  8,  2, 35, 84, 72, 48, 78, 86, 87, 58,  0, 49, 14, 55, 11,
       73, 39, 26, 75, 27, 99, 46, 25, 22, 34, 83, 24, 47, 31, 57, 62, 19,
       36, 15, 17, 10, 98, 90]

After =>

[63, 84, 72, 78, 86, 87, 58, 55, 73, 75, 99, 83, 57, 62, 98, 90]

```

In [70]:
arr = np.random.choice(100, 40, replace=False) 
#교체가 없음. 중복이 없다는 뜻. 비 복원 추출.
#주머니 안에서 1,2,3,4를 뽑았을 때, 2를 뽑았는데 그 다음 뽑을 때 2가 없는 것.
arr

array([20, 78, 49, 89, 47, 41, 51, 96, 65, 36,  1,  7, 56, 30, 71, 23, 64,
        8, 35, 11, 48, 92,  5, 18, 63, 57, 14, 77, 40, 88, 29, 99, 21, 24,
       72, 25, 94, 97, 53, 17])

In [71]:
arr[arr>50] #내가해냄
#불린 인덱싱

array([78, 89, 51, 96, 65, 56, 71, 64, 92, 63, 57, 77, 88, 99, 72, 94, 97,
       53])

In [73]:
#강사님 =>????????
arr[arr.where(arr>50)]
#펜싱 인덱싱
#인덱싱값 반환

AttributeError: 'numpy.ndarray' object has no attribute 'where'

#### Quiz 11
```
kor = np.array( [60,55,70,30,20,90])
1. 국어점수가 가장큰값을 구하여라
2. 국어점수가 80점이상인 값을 구하여라
3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
4. 국어점수의 평균을 구하여라
5. 국어점수의 총합을 구하여라.
6. 국어점수가 40점이하인 데이터를 삭제하여라
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
8. 국어점수 top 3를 구하여라
9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요

60 '불합격'
55 '불합격'
```

In [58]:
kor = np.array( [60,55,70,30,20,90])
a = kor.max()
a

90

In [59]:
b = kor>=80
b

array([False, False, False, False, False,  True])

In [60]:
c = (50 <= kor) & (kor <=80)
c

array([ True,  True,  True, False, False, False])

In [ ]:
4번


In [61]:
e = sum(np.array)
e

TypeError: 'builtin_function_or_method' object is not iterable

In [ ]:
6번 = 이

In [54]:
7번

SyntaxError: invalid decimal literal (3784543964.py, line 1)

In [55]:
8번

SyntaxError: invalid decimal literal (3084616411.py, line 1)

In [ ]:
9번

In [74]:
#강사님
kor = np.array( [60,55,70,30,20,90])

In [75]:
max(kor)

90

In [76]:
kor[(kor>=80)]

array([90])

In [77]:
kor[(kor>=50) & (kor <=80)]

array([60, 55, 70])

In [78]:
np.average(kor), round(kor.mean(), 3)

(54.166666666666664, 54.167)

In [79]:
np.sum(kor)

325

In [81]:
import copy
kor1 = kor.copy()
num = kor[kor<=40]
kor1, num, np.delete(kor1, np.where(kor<=40))

(array([60, 55, 70, 30, 20, 90]), array([30, 20]), array([60, 55, 70, 90]))

In [82]:
np.where(kor>=50, kor*1.1, kor)

array([66. , 60.5, 77. , 30. , 20. , 99. ])

In [84]:
np.sort(kor)[::-1][:3], kor[np.argsort(kor)[::-1][:3]] #인덱스 값으로 실제 값 출력

(array([90, 70, 60]), array([90, 70, 60]))

In [85]:
np.argsort(kor)[::-1][:3]

array([5, 2, 0], dtype=int64)

In [86]:
kor, np.where(kor>=70, "합격", "불합격")

(array([60, 55, 70, 30, 20, 90]),
 array(['불합격', '불합격', '합격', '불합격', '불합격', '합격'], dtype='<U3'))